title: 简历 - c++ 开发工程师 - 微微

aboutme: 
  name: 微微
  sex: 男
  age: 23
  edu: 本科
  job: c++ 工程师
  city: 北京
  email: lostprobe@gmail.com
  phone: 10086
  github: https://github.com/lostprobe99

update: 2020年5月26日
